# evaluate.py — Fixed evaluation harness
#
# DO NOT EDIT THIS FILE.
# This is the trusted measurement contract between the human and the agent.
# The agent's only job is to minimize `val_mse` as reported here.
#
# How it works:
#   1. Load data/dataset.csv and split into 80 train / 20 val rows (fixed seed).
#   2. Call train.train_and_predict(train_X, train_y, val_X) from the agent's file.
#   3. Compute Mean Squared Error between the predictions and the true val_y.
#   4. Print structured output that the agent parses (grep for "val_mse:").
#
# Run from the project root:
#   python src/evaluate.py > run.log 2>&1

import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

# Dataset lives one level up from src/
DATA_PATH = Path(__file__).parent.parent / "data" / "dataset.csv"

# Fixed seed ensures identical train/val split every run — makes results comparable
RANDOM_SEED = 42


def load_and_split():
    """Load the CSV and return a fixed 80/20 train/val split."""
    df = pd.read_csv(DATA_PATH)
    X = df[["x1", "x2"]].to_numpy()
    y = df["y"].to_numpy()
    return train_test_split(X, y, test_size=0.2, random_state=RANDOM_SEED)


def compute_mse(predictions: np.ndarray, val_y: np.ndarray) -> float:
    """Compute MSE safely — returns float('inf') instead of raising on bad input."""
    try:
        predictions = np.asarray(predictions, dtype=float)
        # Wrong number of predictions → can't score
        if predictions.shape != val_y.shape:
            return float("inf")
        # NaN or Inf predictions → treat as failure
        if not np.all(np.isfinite(predictions)):
            return float("inf")
        return float(mean_squared_error(val_y, predictions))
    except Exception:
        return float("inf")


def main():
    # Import train.py from the same directory (the agent edits this file)
    sys.path.insert(0, str(Path(__file__).parent))
    import train  # noqa: PLC0415

    train_X, val_X, train_y, val_y = load_and_split()

    t0 = time.perf_counter()
    try:
        predictions = train.train_and_predict(train_X, train_y, val_X)
    except Exception as e:
        # Catch any crash inside train.py and report it as inf rather than dying
        elapsed = time.perf_counter() - t0
        print(f"CRASH: {e}")
        print(f"val_mse:          inf")
        print(f"elapsed_seconds:  {elapsed:.1f}")
        print(f"num_rows_train:   {len(train_X)}")
        print(f"num_rows_val:     {len(val_X)}")
        return

    elapsed = time.perf_counter() - t0
    val_mse = compute_mse(predictions, val_y)

    # Fixed-width output so the agent can reliably grep "val_mse:"
    print(f"val_mse:          {val_mse:.6f}")
    print(f"elapsed_seconds:  {elapsed:.1f}")
    print(f"num_rows_train:   {len(train_X)}")
    print(f"num_rows_val:     {len(val_X)}")


if __name__ == "__main__":
    main()
